apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: label-component
spec:
  workload:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: label-nginx
      labels:
        app: nginx
        definition.oam.dev/unique-pod: pod-template-hash
    spec:
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
            - name: nginx
              image: nginx:1.17
              ports:
                - containerPort: 80
