apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foo.example.com
spec:
  group: example.com
  names:
    kind: Foo
    listKind: FooList
    plural: foo
    singular: foo
  scope: Namespaced
  version: v1
