apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foo.example.com
spec:
  group: example.com
  names:
    kind: Foo
    listKind: FooList
    plural: foo
    singular: foo
  scope: Namespaced
  version: v1
---
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: foo.example.com
spec:
  definitionRef:
    name: foo.example.com
---
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: foo.example.com
spec:
  definitionRef:
    name: foo.example.com
