apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oam-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oam-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
